/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/actions/{action_id}/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Draft */
        post: operations["draft_api_actions__action_id__draft_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload */
        post: operations["upload_api_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/intake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Intake */
        post: operations["intake_api_intake_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Review */
        patch: operations["review_api_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspace */
        get: operations["workspace_api_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Action */
        Action: {
            /** @default not_required */
            approval_status: components["schemas"]["ApprovalStatus"];
            /**
             * Burden
             * @default 1
             */
            burden: number;
            /** Description */
            description: string;
            /**
             * Earliest Date
             * Format: date
             */
            earliest_date: string;
            /** Effects */
            effects?: components["schemas"]["Effect"][];
            /** Excludes */
            excludes?: string[];
            /**
             * Fee Cents
             * @default 0
             */
            fee_cents: number;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "shift" | "cancel" | "claim" | "request" | "keep";
            /**
             * Latest Date
             * Format: date
             */
            latest_date: string;
            /**
             * Preserves Essential Services
             * @default true
             */
            preserves_essential_services: boolean;
            /**
             * Recommended Date
             * Format: date
             */
            recommended_date: string;
            /** Requires */
            requires?: string[];
            /** @default pending */
            review_status: components["schemas"]["ReviewStatus"];
            /** Service Id */
            service_id?: string | null;
            /** Source Rule Ids */
            source_rule_ids: string[];
            /** Title */
            title: string;
        };
        /**
         * ApprovalStatus
         * @enum {string}
         */
        ApprovalStatus: "not_required" | "pending" | "approved" | "denied";
        /** Condition */
        Condition: {
            /** Fact */
            fact: string;
            /**
             * Operator
             * @default eq
             * @enum {string}
             */
            operator: "eq" | "gte" | "lte" | "exists";
            /**
             * Resolved
             * @default false
             */
            resolved: boolean;
            /** Satisfied */
            satisfied?: boolean | null;
            /** Value */
            value?: string | number | boolean | null;
        };
        /** DailyBalance */
        DailyBalance: {
            /** Balance Cents */
            balance_cents: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Event Ids */
            event_ids?: string[];
            /** Expense Cents */
            expense_cents: number;
            /** Income Cents */
            income_cents: number;
        };
        /** DependencyGraph */
        DependencyGraph: {
            /** Edges */
            edges?: components["schemas"]["GraphEdge"][];
            /** Issues */
            issues?: components["schemas"]["GraphIssue"][];
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][];
        };
        /** Document */
        Document: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Media Type */
            media_type: string;
            /** Name */
            name: string;
            /** Pages */
            pages?: components["schemas"]["DocumentPage"][];
            /** Sha256 */
            sha256: string;
            /**
             * Status
             * @default uploaded
             * @enum {string}
             */
            status: "uploaded" | "extracting" | "needs_review" | "ready" | "failed";
            /**
             * Synthetic
             * @default false
             */
            synthetic: boolean;
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** DocumentPage */
        DocumentPage: {
            /** Page */
            page: number;
            /** Text */
            text: string;
        };
        /** DraftResponse */
        DraftResponse: {
            /** Action Id */
            action_id: string;
            /** Body */
            body: string;
            /**
             * Sent
             * @default false
             * @constant
             */
            sent: false;
            /** Subject */
            subject: string;
        };
        /** Effect */
        Effect: {
            /** Date */
            date?: string | null;
            event?: components["schemas"]["FinancialEvent"] | null;
            /** Offset Days */
            offset_days?: number | null;
            /**
             * Operation
             * @enum {string}
             */
            operation: "shift" | "remove" | "add" | "accelerate";
            /** Target Event Id */
            target_event_id?: string | null;
        };
        /** Evidence */
        Evidence: {
            /** Char End */
            char_end: number;
            /** Char Start */
            char_start: number;
            /** Document Id */
            document_id: string;
            /** Page */
            page: number;
            /** Quote */
            quote: string;
            /**
             * Version
             * @default 1
             */
            version: number;
        };
        /** FinancialEvent */
        FinancialEvent: {
            /** Amount Cents */
            amount_cents: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "income" | "expense";
            /**
             * Essential
             * @default false
             */
            essential: boolean;
            /** Id */
            id: string;
            /**
             * Kind
             * @default projected
             * @enum {string}
             */
            kind: "actual" | "projected";
            /** Obligation Id */
            obligation_id?: string | null;
            /** Service Id */
            service_id?: string | null;
            /** Source Rule Ids */
            source_rule_ids?: string[];
            /** Title */
            title: string;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Id */
            id: string;
            /** Label */
            label?: string | null;
            /**
             * Relation
             * @enum {string}
             */
            relation: "requires" | "triggers" | "excludes" | "supersedes" | "supports";
            /** Rule Ids */
            rule_ids?: string[];
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** GraphIssue */
        GraphIssue: {
            /**
             * Blocking
             * @default true
             */
            blocking: boolean;
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Rule Ids */
            rule_ids?: string[];
        };
        /** GraphNode */
        GraphNode: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "document" | "rule" | "action" | "event" | "entity";
            /** Label */
            label: string;
            /** Reference Id */
            reference_id: string;
            /** Status */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntakeRequest */
        IntakeRequest: {
            /** Essential Service Ids */
            essential_service_ids?: string[];
            /** Events */
            events: components["schemas"]["FinancialEvent"][];
            /**
             * Horizon Days
             * @default 60
             */
            horizon_days: number;
            /** Opening Balance Cents */
            opening_balance_cents: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
        };
        /** JobStatus */
        JobStatus: {
            /** Document Id */
            document_id?: string | null;
            /** Error */
            error?: string | null;
            /** Id */
            id: string;
            /** Progress */
            progress: number;
            /** Stage */
            stage: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PlanRequest */
        PlanRequest: {
            /** Action Dates */
            action_dates?: {
                [key: string]: string;
            };
            /** Approval Overrides */
            approval_overrides?: {
                [key: string]: components["schemas"]["ApprovalStatus"];
            };
            /** Exclude Action Ids */
            exclude_action_ids?: string[];
            /** Force Action Ids */
            force_action_ids?: string[];
            /** Horizon Days */
            horizon_days?: number | null;
            /**
             * Include Conditional
             * @default false
             */
            include_conditional: boolean;
            /** Income Cents */
            income_cents?: number | null;
            /** Income Date */
            income_date?: string | null;
            /** Opening Balance Cents */
            opening_balance_cents?: number | null;
        };
        /** PlanResult */
        PlanResult: {
            /** Actions */
            actions: components["schemas"]["PlannedAction"][];
            baseline: components["schemas"]["Simulation"];
            /** Excluded Actions */
            excluded_actions?: {
                [key: string]: string;
            };
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Id */
            id: string;
            /**
             * Objective Proven
             * @default false
             */
            objective_proven: boolean;
            proposed: components["schemas"]["Simulation"];
            /**
             * Revision
             * @default 1
             */
            revision: number;
            /**
             * Solver Status
             * @enum {string}
             */
            solver_status: "OPTIMAL" | "FEASIBLE" | "INFEASIBLE" | "UNKNOWN" | "MODEL_INVALID";
            /** Solver Wall Time Seconds */
            solver_wall_time_seconds: number;
            /**
             * State
             * @enum {string}
             */
            state: "confirmed" | "conditional" | "infeasible" | "unresolved";
            /** Warnings */
            warnings?: string[];
        };
        /** PlannedAction */
        PlannedAction: {
            /** Action Id */
            action_id: string;
            /**
             * Conditional
             * @default false
             */
            conditional: boolean;
            /**
             * Execution Date
             * Format: date
             */
            execution_date: string;
            /** Explanation */
            explanation: string;
            /** Order */
            order: number;
            /** Source Rule Ids */
            source_rule_ids: string[];
        };
        /** ProviderStatus */
        ProviderStatus: {
            /** Configured */
            configured: boolean;
            /** Detail */
            detail: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "offline" | "unavailable";
            /** Model */
            model?: string | null;
            /** Name */
            name: string;
        };
        /**
         * ReviewStatus
         * @enum {string}
         */
        ReviewStatus: "pending" | "reviewed" | "rejected" | "unresolved";
        /** Rule */
        Rule: {
            /** Amount Cents */
            amount_cents?: number | null;
            /** @default not_required */
            approval_status: components["schemas"]["ApprovalStatus"];
            /** Conditions */
            conditions?: components["schemas"]["Condition"][];
            /**
             * Consequential
             * @default true
             */
            consequential: boolean;
            /** Dependencies */
            dependencies?: string[];
            /** Due Date */
            due_date?: string | null;
            /**
             * Entity Ambiguous
             * @default false
             */
            entity_ambiguous: boolean;
            /** Evidence */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Evidence Status
             * @default unchecked
             * @enum {string}
             */
            evidence_status: "unchecked" | "supported" | "disputed" | "unsupported";
            /**
             * Extraction Confidence
             * @default 0
             */
            extraction_confidence: number;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "obligation" | "benefit" | "option" | "constraint";
            /** Parties */
            parties?: string[];
            /** @default pending */
            review_status: components["schemas"]["ReviewStatus"];
            /** Supersedes */
            supersedes?: string[];
            /** Title */
            title: string;
            /** Verifier Notes */
            verifier_notes?: string | null;
        };
        /** RuleReview */
        RuleReview: {
            /** Amount Cents */
            amount_cents?: number | null;
            approval_status?: components["schemas"]["ApprovalStatus"] | null;
            /** Conditions */
            conditions?: components["schemas"]["Condition"][] | null;
            /** Due Date */
            due_date?: string | null;
            /** Note */
            note?: string | null;
            review_status: components["schemas"]["ReviewStatus"];
        };
        /** Scenario */
        Scenario: {
            /** Actions */
            actions: components["schemas"]["Action"][];
            /** Essential Service Ids */
            essential_service_ids?: string[];
            /** Events */
            events: components["schemas"]["FinancialEvent"][];
            /**
             * Horizon Days
             * @default 60
             */
            horizon_days: number;
            /** Id */
            id: string;
            /** Opening Balance Cents */
            opening_balance_cents: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Title */
            title: string;
        };
        /** Simulation */
        Simulation: {
            /** Additional Cash Required Cents */
            additional_cash_required_cents: number;
            /** Beyond Horizon */
            beyond_horizon?: components["schemas"]["FinancialEvent"][];
            /** Daily */
            daily: components["schemas"]["DailyBalance"][];
            /** Ending Balance Cents */
            ending_balance_cents: number;
            /** First Shortfall Date */
            first_shortfall_date: string | null;
            /** Minimum Balance Cents */
            minimum_balance_cents: number;
        };
        /** UploadResponse */
        UploadResponse: {
            document: components["schemas"]["Document"];
            /**
             * Duplicate
             * @default false
             */
            duplicate: boolean;
            job?: components["schemas"]["JobStatus"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Workspace */
        Workspace: {
            /** Documents */
            documents: components["schemas"]["Document"][];
            graph: components["schemas"]["DependencyGraph"];
            /** Jobs */
            jobs?: components["schemas"]["JobStatus"][];
            /**
             * Mode
             * @enum {string}
             */
            mode: "synthetic" | "live";
            plan?: components["schemas"]["PlanResult"] | null;
            /** Providers */
            providers?: components["schemas"]["ProviderStatus"][];
            /** Revision */
            revision: number;
            /** Rules */
            rules: components["schemas"]["Rule"][];
            scenario: components["schemas"]["Scenario"];
            /** Session Id */
            session_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    draft_api_actions__action_id__draft_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                action_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_api_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponse"];
                };
            };
        };
    };
    intake_api_intake_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_api_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleReview"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workspace_api_workspace_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
        };
    };
}
