import type { components } from "./api-types";

export type Workspace = components["schemas"]["Workspace"];
export type Scenario = components["schemas"]["Scenario"];
export type Rule = components["schemas"]["Rule"];
export type Action = components["schemas"]["Action"];
export type FinancialEvent = components["schemas"]["FinancialEvent"];
export type PlanResult = components["schemas"]["PlanResult"];
export type Simulation = components["schemas"]["Simulation"];
export type PlanRequest = components["schemas"]["PlanRequest"];
export type RuleReview = components["schemas"]["RuleReview"];
export type IntakeRequest = components["schemas"]["IntakeRequest"];
export type UploadResponse = components["schemas"]["UploadResponse"];
export type DraftResponse = components["schemas"]["DraftResponse"];
export type ProviderStatus = components["schemas"]["ProviderStatus"];
export type JobStatus = components["schemas"]["JobStatus"];
export type ApprovalStatus = components["schemas"]["ApprovalStatus"];
export type VerificationRequest = components["schemas"]["VerificationRequest"];
export type VerificationResult = components["schemas"]["VerificationResult"];
export type ReviewQueue = components["schemas"]["ReviewQueue"];
export type ReviewQueueItem = components["schemas"]["ReviewQueueItem"];
